### ISSUE TITLE
Errors while trying to launch.

### ISSUE THREAD

**Issue by Jakonix** [SpaceWalkerRS/kabo-village-marker#2]
Loader: legacyfabric-1.7.10+loader.0.16.7
OSL: ornithe-standard-libraries-0.11.2
Other mods:
legacy-fixes-1.0.1

Error:
Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'client-init' due to errors, provided by 'kabo-village-marker' at 'kabopc.village_marker.KaboVillageMarkerMod'!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:482)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'client-init' due to errors, provided by 'kabo-village-marker' at 'kabopc.village_marker.KaboVillageMarkerMod'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
	at knot//net.minecraft.client.main.Main.handler$zzb000$osl-entrypoints$osl$entrypoints$init(Main.java:529)
	at knot//net.minecraft.client.main.Main.main(Main.java)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	... 10 more
	Suppressed: java.lang.NoClassDefFoundError: net/minecraft/unmapped/C_8105098
		at knot//net.ornithemc.osl.config.impl.client.ClientConfigInitializer.initClient(ClientConfigInitializer.java:13)
		at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)
		... 13 more
	Caused by: java.lang.ClassNotFoundException: net.minecraft.unmapped.C_8105098
		at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
		at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
		at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
		at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
		... 15 more
	Suppressed: java.lang.NoClassDefFoundError: net/minecraft/unmapped/C_8105098
		at knot//net.ornithemc.osl.networking.impl.Networking.initClient(Networking.java:39)
		at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)
		... 13 more
	Caused by: java.lang.ClassNotFoundException: net.minecraft.unmapped.C_8105098
		at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
		at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
		at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
		at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
		... 15 more
	Suppressed: java.lang.NoClassDefFoundError: net/minecraft/unmapped/C_8105098
		at knot//net.ornithemc.osl.resource.loader.impl.ResourceLoader.initClient(ResourceLoader.java:31)
		at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)
		... 13 more
	Caused by: java.lang.ClassNotFoundException: net.minecraft.unmapped.C_8105098
		at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
		at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
		at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
		at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
		... 15 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/unmapped/C_8105098
	at knot//kabopc.village_marker.KaboVillageMarkerMod.initClient(KaboVillageMarkerMod.java:38)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)
	... 13 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.unmapped.C_8105098
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 15 more

I think it might be mapping problem but idk.

**Comment by SpaceWalkerRS** [comment]
Both OSL and Kabo Village Marker are Ornithe mods, they cannot be run on Legacy Fabric.

**Comment by Jakonix** [comment]
What loader should i use then for 1.7.10.

**Comment by SpaceWalkerRS** [comment]
Ornithe: https://ornithemc.net

**Comment by SpaceWalkerRS** [comment]
do keep in mind Ornithe mods and Legacy Fabric mods are not intercompatible

**Comment by Jakonix** [comment]
Ok everything works now thank you very much.
